### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by johnwahlig** [FalmouthCPC/hwh#11]
Because honestly "homework helper" is a little bland.

minor issue, but just keep it in the back of your mind.

**Comment by rpbritton** [comment]
hewmwerk heelpster?

**Comment by rpbritton** [comment]
Liam's List:
```
Astrel
Leebra
Duffie
Mittat
Oximen
Labora
Domum Monumentum
Opus Monumentum
```

**Comment by johnwahlig** [comment]
what are you on Liam?

**Comment by rpbritton** [comment]
So Duffie it is?

**Comment by johnwahlig** [comment]
*not Drexel for Yahweh's sake*
